// This file deals with opening the PDF invoices generated by the user
// It also handles images

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openPDF: (pdfPath) => {
    console.log('Opening PDF:', pdfPath);
    ipcRenderer.send('open-pdf', pdfPath);
  },
  getImagePath: (imagePath) => {
    return `http://localhost:3001/images/${imagePath}`
  }
});